Update release_build.yml

diff --git a/.github/workflows/release_build.yml b/.github/workflows/release_build.yml
--- a/.github/workflows/release_build.yml
+++ b/.github/workflows/release_build.yml
@@ -34,7 +34,7 @@ jobs:
         run: echo "manifest=$(< ./NewHorizons/manifest.json sed ':a;N;$!ba;s/\n/ /g')" >> $GITHUB_OUTPUT
       - name: Error
         if: ${{ steps.read-manifest.outputs.version != github.event.pull_request.title }}
-        run: echo "::error file=manifest.json,title=Version Error::Hey DUMB-DUMB UPDATE THE MANIFEST VERSION"
+        run: echo "::error file=manifest.json,title=Version Error::Hey DUMB-DUMB UPDATE THE MANIFEST VERSION" && exit 1
   Build:
     needs: Check_Version
     if: ${{ needs.Check_Version.result == 'success' && (github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'update-pr'))  }}
